Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2020-10, with the labels that each got.

#289 Bugfix for locating anglerfish sample sheet
  taca/analysis/analysis_nanopore.py
  tests/test_analysis_nanopore.py
Labels: no validation

#290 Find minknow output files that were renamed in the latest version
  taca/analysis/analysis_nanopore.py
Labels: no validation

#291 Support 10X Visium index type
  taca/illumina/HiSeqX_Runs.py
Labels: enhancement, no validation

#293 Add support for Smart-seq index sets
  taca/illumina/HiSeqX_Runs.py
  tests/data/2014/FCIDXX.csv
  tests/data/RunInfo.xml
  tests/data/samplesheet_sample_check.csv
  tests/data/taca_test_cfg.yaml
  tests/data/test_10X_indexes
  tests/data/test_smartseq_indexes
  tests/test_illumina.py
Labels: no validation

#294 Fix issue that free space on NAS is not correctly parsed after server…
  taca/backup/backup.py
Labels: bug, no validation

#295 Change the way how samples are sorted
  taca/illumina/HiSeqX_Runs.py
  tests/data/2014/FCIDXX.csv
  tests/test_illumina.py
Labels: no validation
