Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2023-09, with the labels that each got.

#370 Refactor archiving for moving to ngi-nas
  taca/backup/backup.py
  taca/cleanup/cleanup.py
  taca/cleanup/cli.py
  taca/utils/filesystem.py
  taca/utils/misc.py
Labels: validation

#380 Adapt MinKNOW .json trimming to new format from Dorado update
  VERSIONLOG.md
  taca/__init__.py
  taca/nanopore/nanopore.py
Labels: bug, enhancement, no validation

#381 Fix bugs for encrypting and archiving runs on ngi-preproc
  VERSIONLOG.md
  taca/backup/backup.py
  taca/utils/misc.py
Labels: bug, no validation

#385 Write archived file names to log
  taca/backup/backup.py
Labels: no validation

#387 Fix bugs for encrypting and archiving runs on ngi-preproc
  VERSIONLOG.md
  taca/backup/backup.py
Labels: bug, no validation

#386 MinION renovation
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis_nanopore.py
  taca/analysis/cli.py
  taca/nanopore/ONT_run_classes.py
  taca/nanopore/instrument_transfer.py
  taca/nanopore/minion.py
  taca/nanopore/nanopore.py
  taca/nanopore/ont_transfer.py
  taca/utils/minion_barcodes.py
  taca/utils/statusdb.py
  tests/test_nanopore.py
Labels: enhancement, WIP, no validation

#388 Minion renovation supplement
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis_nanopore.py
  taca/analysis/cli.py
  taca/nanopore/ONT_run_classes.py
  taca/nanopore/instrument_transfer.py
Labels: enhancement, no validation

#389 Remove the temp change of creating links
  VERSIONLOG.md
  taca/illumina/Runs.py
Labels: bug, no validation

#390 Fix bug that NovaSeqXPlus date format cause error in writing pdc_archived timestamp
  VERSIONLOG.md
  taca/backup/backup.py
Labels: bug, no validation
