Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2023-08, with the labels that each got.

#371 Expand PromethION QC log query
  VERSIONLOG.md
  taca/nanopore/promethion_transfer.py
Labels: enhancement, no validation

#372 Refactor handling of MinION QC runs
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis_nanopore.py
  taca/analysis/cli.py
  taca/nanopore/minion.py
  taca/nanopore/nanopore.py
  tests/test_nanopore.py
Labels: no validation

#373 Implement logging for PromethION script
  VERSIONLOG.md
  taca/nanopore/promethion_transfer.py
Labels: enhancement, no validation

#374 pmub (backwards bump)
  taca/nanopore/promethion_transfer.py
Labels: Documentation, no validation

#377 Set up copying of ONT metadata, calc new metrics and improve modularization
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis_nanopore.py
  taca/nanopore/nanopore.py
  taca/nanopore/ont_transfer.py
Labels: enhancement, no validation

#378 Add pandas to requirements
  VERSIONLOG.md
  requirements.txt
Labels: Documentation, no validation

#379 Allow database update of finished ONT runs
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis_nanopore.py
  taca/analysis/cli.py
  taca/nanopore/nanopore.py
Labels: enhancement, no validation
