Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-12, with the labels that each got.

#447 Stage ONT data for delivery
  VERSIONLOG.md
  setup.py
  taca/__init__.py
  taca/delivery/__init__.py
  taca/delivery/cli.py
  taca/delivery/deliver.py
  taca/delivery/delivery_classes.py
Labels: no validation

#448 ONT automated QC reports with ToulligQC
  VERSIONLOG.md
  taca/analysis/analysis_nanopore.py
  taca/nanopore/ONT_run_classes.py
  tests/analysis/test_analysis_nanopore.py
  tests/conftest.py
  tests/nanopore/test_ONT_run_classes.py
Labels: enhancement, no validation

#451 ToulligQC fixes
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
  tests/conftest.py
  tests/nanopore/test_ONT_run_classes.py
Labels: bug, enhancement, no validation

#449 Upload ONT data to DDS
  VERSIONLOG.md
  requirements.txt
  taca/__init__.py
  taca/delivery/cli.py
  taca/delivery/deliver.py
  taca/delivery/delivery_classes.py
Labels: no validation

#453 Change server_status nas to update statusdb by default
  VERSIONLOG.md
  taca/server_status/cli.py
Labels: no validation

#455 Free column 3 of PromethION
  VERSIONLOG.md
  taca/nanopore/instrument_transfer.py
  tests/nanopore/test_instrument_transfer.py
Labels: enhancement, no validation

#446 Add ONT FCs to bioinfo tab
  VERSIONLOG.md
  taca/utils/bioinfo_tab.py
  taca/utils/cli.py
Labels: no validation

#458 Forgot to commit fix in PR: Add ONT FCs to bioinfo tab #446
  VERSIONLOG.md
  taca/utils/bioinfo_tab.py
Labels: no validation

#454 Fix missing samplesheet issue
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis.py
  taca/illumina/Runs.py
Labels: no validation

#459 Skip ToulligQC
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
Labels: bug, enhancement, no validation
