Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-01, with the labels that each got.

#399 Version V1.0.0
  VERSIONLOG.md
  taca/__init__.py
  taca/analysis/analysis.py
  taca/analysis/cli.py
  taca/backup/backup.py
  taca/illumina/HiSeqX_Runs.py
  taca/illumina/HiSeq_Runs.py
  taca/illumina/MiSeq_Runs.py
  taca/illumina/NextSeq_Runs.py
  taca/illumina/NovaSeqXPlus_Runs.py
  taca/illumina/NovaSeq_Runs.py
  taca/illumina/Runs.py
  taca/illumina/Standard_Runs.py
  tests/data/taca_test_cfg.yaml
  tests/test_analysis.py
  tests/test_illumina.py
Labels: enhancement, validation

#402 Hotfix of bugs
  taca/illumina/Runs.py
Labels: bug, no validation

#403 Initial PR, tests for the ONT transfer script
  .gitignore
  requirements-dev.txt
  requirements.txt
  taca/nanopore/instrument_transfer.py
  tests/.coveragerc
  tests/test_instrument_transfer.py
Labels: enhancement, no validation

#404 Fix typo
  taca/illumina/MiSeq_Runs.py
  taca/illumina/NextSeq_Runs.py
  taca/illumina/NovaSeqXPlus_Runs.py
  taca/illumina/NovaSeq_Runs.py
  taca/illumina/Standard_Runs.py
Labels: bug, no validation

#406 Remove unused travis building and badge
  .travis.yml
  README.md
Labels: no validation

#407 Adapt to new(?) STUPID json format
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
Labels: bug, enhancement, no validation

#408 Adapt to new ONT pod5 format
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
Labels: enhancement, no validation

#409 Update how Anglerfish is applied
  taca/analysis/analysis_nanopore.py
  taca/nanopore/ONT_run_classes.py
Labels: enhancement, no validation
