Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-05, with the labels that each got.

#424 Broaden ONT transfer script's categorization of QC runs
  VERSIONLOG.md
  taca/nanopore/instrument_transfer.py
  taca/utils/misc.py
Labels: enhancement, no validation

#425 Fix erroneous name of pod5 output dir for ONT runs
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
Labels: bug, no validation

#427 Update server status to reflect ngi-preproc
  VERSIONLOG.md
  taca/server_status/server_status.py
Labels: no validation
