Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-10, with the labels that each got.

#434 Update taca-ngi-pipeline repo url
  README.md
  VERSIONLOG.md
Labels: no validation

#435 Switch to tarball and skip compression
  VERSIONLOG.md
  taca/analysis/analysis.py
  taca/backup/backup.py
  taca/backup/cli.py
  tests_old/test_backup.py
Labels: enhancement, validation

#432 Initial setup for element aviti
  .devcontainer/devcontainer.json
  .github/workflows/lint-code.yml
  .github/workflows/test-code.yml
  Dockerfile
  VERSIONLOG.md
  pyproject.toml
  requirements-dev.txt
  setup.py
  taca/__init__.py
  taca/analysis/analysis_element.py
  taca/analysis/cli.py
  taca/element/Aviti_Runs.py
  taca/element/Element_Runs.py
  taca/element/__init__.py
  taca/utils/statusdb.py
  tests/analysis/test_analysis_element.py
  tests/analysis/test_analysis_nanopore.py
  tests/conftest.py
  tests/element/__init__.py
  tests/element/test_Aviti_Runs.py
  tests/element/test_Element_Runs.py
  tests/nanopore/test_ONT_run_classes.py
Labels: validation

#436 Fix TACA for handling 10X UMI cases by BCL Convert
  VERSIONLOG.md
  taca/illumina/Standard_Runs.py
Labels: enhancement, no validation

#437 Fix for Tiny bug in reading the transfer log
  VERSIONLOG.md
  taca/analysis/analysis_element.py
  taca/element/Element_Runs.py
  tests/element/test_Element_Runs.py
Labels: no validation

#438 Fix issue that index 2 is automatically converted to RC by BCL Convert
  VERSIONLOG.md
  taca/illumina/NovaSeqXPlus_Runs.py
Labels: bug, validation

#439 Fix missing settings for BCL Convert
  VERSIONLOG.md
  taca/illumina/NextSeq_Runs.py
  taca/illumina/NovaSeqXPlus_Runs.py
  taca/illumina/NovaSeq_Runs.py
  taca/illumina/Runs.py
Labels: bug, validation
