Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-02, with the labels that each got.

#412 Fix bugs that changs in PR #404 were reverted in PR #411
  VERSIONLOG.md
  taca/illumina/Standard_Runs.py
Labels: bug, no validation

#410 More improvements on TACA running Anglerfish
  VERSIONLOG.md
  taca/nanopore/ONT_run_classes.py
Labels: enhancement, no validation

#413 Implement CI testing and increase testing coverage
  .devcontainer/devcontainer.json
  .github/workflows/test-code.yml
  .gitignore
  .pre-commit-config.yaml
  VERSIONLOG.md
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  taca/nanopore/ONT_run_classes.py
  taca/nanopore/instrument_transfer.py
  taca/utils/filesystem.py
  taca/utils/transfer.py
  tests/.coveragerc
  tests/pytest/conftest.py
  tests/pytest/test_ONT_run_classes.py
  tests/pytest/test_analysis_nanopore.py
  tests/pytest/test_instrument_transfer.py
Labels: bug, enhancement, no validation

#415 Try integrating CodeCov in GHA
  .github/workflows/test-code.yml
Labels: enhancement, help wanted, no validation

#416 Implement CodeCoverage
  .github/workflows/test-code.yml
  VERSIONLOG.md
Labels: Documentation, enhancement, no validation
