Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2024-11, with the labels that each got.

#440 Fix extra postfix in sample names for BCL Convert
  VERSIONLOG.md
  taca/illumina/Runs.py
Labels: bug, validation

#441 Add Aviti FCs to bioinfo tab
  VERSIONLOG.md
  taca/element/Element_Runs.py
  taca/utils/bioinfo_tab.py
Labels: no validation

#445 Catch exception in case lane is numeric as is the case with older flowcells
  VERSIONLOG.md
  taca/utils/bioinfo_tab.py
Labels: no validation

#444 Organising flowcell data on Miarka
  VERSIONLOG.md
  setup.py
  taca/__init__.py
  taca/backup/backup.py
  taca/cleanup/cleanup.py
  taca/organise/__init__.py
  taca/organise/cli.py
  taca/organise/flowcells.py
  taca/organise/organise.py
  taca/utils/filesystem.py
  tests/element/test_Element_Runs.py
Labels: no validation

#443 Add automated cleanup to ONT instrument transfer script
  VERSIONLOG.md
  taca/nanopore/instrument_transfer.py
  tests/nanopore/test_instrument_transfer.py
Labels: enhancement, no validation
