Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2025-01, with the labels that each got.

#461 Ruff format
  VERSIONLOG.md
  taca/cleanup/cleanup.py
  taca/element/Element_Runs.py
  taca/nanopore/ONT_run_classes.py
  taca/utils/misc.py
  taca/utils/statusdb.py
  taca/utils/transfer.py
  tests/nanopore/test_ONT_run_classes.py
  tests/nanopore/test_instrument_transfer.py
Labels: enhancement, no validation

#460 Improve identifying run dirs
  VERSIONLOG.md
  taca/utils/bioinfo_tab.py
Labels: bug, enhancement, no validation

#457 Try PR label check action
  .github/pr_labels.yml
  .github/workflows/check_pr_label.yml
  VERSIONLOG.md
Labels: no validation
