Repository NationalGenomicsInfrastructure/TACA, pull requests merged in 2025-08, with the labels that each got.

#482 Replace the CouchDB package with IBM cloudant
  README.md
  VERSIONLOG.md
  requirements.txt
  taca/__init__.py
  taca/analysis/analysis.py
  taca/backup/backup.py
  taca/delivery/delivery_classes.py
  taca/server_status/cronjobs.py
  taca/server_status/server_status.py
  taca/utils/bioinfo_tab.py
  taca/utils/misc.py
  taca/utils/statusdb.py
  tests/nanopore/test_instrument_transfer.py
Labels: validation

#483 Add back missed FlowcellRunMetricsConnection check in statusdb
  VERSIONLOG.md
  taca/__init__.py
  taca/utils/statusdb.py
Labels: validation

#484 Fix bug in checking ONT run in statusdb
  VERSIONLOG.md
  taca/__init__.py
  taca/utils/statusdb.py
Labels: no validation

#485 Update ONT script
  VERSIONLOG.md
  taca/nanopore/instrument_transfer.py
  tests/nanopore/test_instrument_transfer.py
Labels: enhancement, no validation
